#pragma once

#ifdef _KERNEL_MODE
#include <ntdef.h>
#include <devioctl.h>
#else
#include <windows.h>
#include <winioctl.h>
#endif

#define IOCTL_READ_MEMORY    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_MEMORY   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ALLOC_MEMORY   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_FREE_MEMORY    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_QUEUE_APC      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNLOAD_DRIVER  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROTECT_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_QUERY_MODULE   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PAYLOAD_BEGIN          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x810, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PAYLOAD_CHUNK          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x811, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PAYLOAD_DECRYPT        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x812, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PAYLOAD_GET_META       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x813, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PAYLOAD_GET_IMPORTS    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x814, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PAYLOAD_SET_IAT        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x815, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PAYLOAD_INJECT         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x816, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PAYLOAD_RELEASE        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x817, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define RH_PAYLOAD_MAX_SIZE          (8 * 1024 * 1024)
#define RH_PAYLOAD_CHUNK_MAX         (32 * 1024)
#define RH_PAYLOAD_KEY_SIZE          32
#define RH_PAYLOAD_IV_SIZE           12
#define RH_PAYLOAD_TAG_SIZE          16

typedef struct _MEMORY_REQUEST {
    HANDLE ProcessId;
    ULONGLONG TargetAddress;
    ULONGLONG BufferAddress;
    SIZE_T Size;
    SIZE_T ReturnSize;
    LONG Status;
    ULONG Reserved;
} MEMORY_REQUEST, *PMEMORY_REQUEST;

typedef struct _ALLOC_REQUEST {
    HANDLE ProcessId;
    ULONGLONG Address;
    SIZE_T Size;
    ULONG AllocationType;
    ULONG Protect;
    LONG Status;
    ULONG Reserved;
} ALLOC_REQUEST, *PALLOC_REQUEST;

typedef struct _FREE_REQUEST {
    HANDLE ProcessId;
    ULONGLONG Address;
    SIZE_T Size;
    ULONG FreeType;
    LONG Status;
    ULONG Reserved;
} FREE_REQUEST, *PFREE_REQUEST;

typedef struct _PROTECT_REQUEST {
    HANDLE ProcessId;
    ULONGLONG Address;
    SIZE_T Size;
    ULONG NewProtect;
    ULONG OldProtect;
    LONG Status;
    ULONG Reserved;
} PROTECT_REQUEST, *PPROTECT_REQUEST;

typedef struct _MODULE_QUERY_REQUEST {
    HANDLE    ProcessId;
    WCHAR     ModuleName[64];
    ULONGLONG BaseAddress;
    SIZE_T    Size;
    LONG      Status;
    ULONG     Reserved;
} MODULE_QUERY_REQUEST, *PMODULE_QUERY_REQUEST;

typedef struct _APC_REQUEST {
    HANDLE ThreadId;
    ULONGLONG NormalRoutine;
    ULONGLONG NormalContext;
    ULONGLONG SystemArgument1;
    ULONGLONG SystemArgument2;
} APC_REQUEST, *PAPC_REQUEST;

typedef struct _PAYLOAD_BEGIN_REQUEST {
    SIZE_T    TotalEncryptedSize;
    UCHAR     SessionKey[RH_PAYLOAD_KEY_SIZE];
    ULONGLONG PayloadId;
} PAYLOAD_BEGIN_REQUEST, *PPAYLOAD_BEGIN_REQUEST;

typedef struct _PAYLOAD_CHUNK_REQUEST {
    ULONGLONG PayloadId;
    ULONG     Offset;
    ULONG     ChunkSize;
} PAYLOAD_CHUNK_REQUEST, *PPAYLOAD_CHUNK_REQUEST;

typedef struct _PAYLOAD_ID_REQUEST {
    ULONGLONG PayloadId;
} PAYLOAD_ID_REQUEST, *PPAYLOAD_ID_REQUEST;

typedef struct _PAYLOAD_META_REQUEST {
    ULONGLONG PayloadId;
    ULONG     SizeOfImage;
    ULONG     EntryPointRva;
    ULONGLONG PreferredBase;
    ULONG     ImportCount;
    ULONG     ImportBlobSize;
    ULONG     RelocationCount;
} PAYLOAD_META_REQUEST, *PPAYLOAD_META_REQUEST;

typedef struct _PAYLOAD_IMP_REQUEST {
    ULONGLONG PayloadId;
    ULONG     BufferSize;
    ULONG     BytesWritten;
} PAYLOAD_IMP_REQUEST, *PPAYLOAD_IMP_REQUEST;

#pragma pack(push, 1)
typedef struct _PAYLOAD_IMP_ENTRY {
    USHORT  DllNameLen;
    USHORT  FuncNameLen;
    USHORT  Ordinal;
    USHORT  Flags;
    ULONG   IatRva;
} PAYLOAD_IMP_ENTRY, *PPAYLOAD_IMP_ENTRY;

typedef struct _PAYLOAD_IAT_ENTRY {
    ULONG     IatRva;
    ULONG     Pad;
    ULONGLONG ResolvedAddress;
} PAYLOAD_IAT_ENTRY, *PPAYLOAD_IAT_ENTRY;
#pragma pack(pop)

typedef struct _PAYLOAD_SET_IAT_REQUEST {
    ULONGLONG PayloadId;
    ULONG     EntryCount;
} PAYLOAD_SET_IAT_REQUEST, *PPAYLOAD_SET_IAT_REQUEST;

typedef struct _PAYLOAD_INJECT_REQUEST {
    ULONGLONG PayloadId;
    HANDLE    TargetPid;
    ULONGLONG TargetBase;
} PAYLOAD_INJECT_REQUEST, *PPAYLOAD_INJECT_REQUEST;
